### ISSUE TITLE
store current configuration to file 

### ISSUE THREAD

**Issue by carmelopellegrino** [MechanicalVentilatorMilano/gui#102]
There shall be a `json`-formatted file written to a read-write partition on the rpi sdcard and another file with the md5sum of the json file.

- [x] on program startup, check of the md5 matches with that of the configuration file and load it if it does.
- [x] when the configuration is updated by the user, the `json`-formatted file is overwritten and the md5 file updated

**Comment by eto-** [comment]
Ciao,
I add the functions to check if the files have the right md5 signature and to create them.
This can easily be integrated with the code reading and writing the json

[md5.txt](https://github.com/MechanicalVentilatorMilano/gui/files/4451449/md5.txt)
