### ISSUE TITLE
initialize the gui with ESP current status

### ISSUE THREAD

**Issue by carmelopellegrino** [MechanicalVentilatorMilano/gui#129]
the ESP32 state machine must act as a master for the GUI state machine.

At program start:
- `get` each setting parameter and initialize the settings panel

Continuously (QTimer)
- `get run` and synchronize the GUI status with it
- `get mode` and synchronize the mode in the GUI (assisted or automatic)
- `get backup`: if the answer is `1` means that the ESP commuted to automatic mode since the last mode setting.

**Comment by marcodeltutto** [comment]
- I will add this to `mock.ino` and `FakeESP32Serial`.
