### ISSUE TITLE
"Resume ventilation" crashes GUI if old file not present

### ISSUE THREAD

**Issue by bs610** [MechanicalVentilatorMilano/gui#148]
If /home/pi/settings.txt is not present, the GUI crashes when the user clicks "Resume Ventilation".

The actual crash is caused by L238 in settings/settings.py, where it tries to access self.config instead of self._config. But I think the program has already gone too far by then. It would seem to make more sense for an error dialog to be presented, rather than silently ignoring the missing file / md5 failure.

**Comment by carmelopellegrino** [comment]
I think the best option here is to test whether the file exists and if not disable the "Resume Ventilation" button.
