### ISSUE TITLE
Misleading dialog created by SnoozeButton

### ISSUE THREAD

**Issue by bs610** [MechanicalVentilatorMilano/gui#217]
When snoozing an alarm (in `SnoozeButton._on_click_snooze`), if communication with the ESP32 fails, the user is presented with 2 buttons (Retry and Abort) that both do nothing. 

Abort should be hooked up to `sys.exit`, and either:
* The Retry button should be hooked up to call `self._on_click_snooze` again, or
* The Retry button should be replaced by an Ok button that does nothing

**Comment by carmelopellegrino** [comment]
same comment as in [issue #216](https://github.com/MechanicalVentilatorMilano/gui/issues/216#issuecomment-621706454)

**Comment by bs610** [comment]
Superseded by issue #238 which will create a common interface for handling ESP32 communication errors.
