### ISSUE TITLE
Parameter defaults/ranges/steps don't match requirements

### ISSUE THREAD

**Issue by bs610** [MechanicalVentilatorMilano/gui#241]
Comparing the current GUI to SRS V2 (https://docs.google.com/document/d/1XK4zHZ3uW7VnTfmBb_SuCsWyzp3vy4BL/edit), the following parameter settings don't match requirements:

* UCR.3: PCV RR max should be 50 not 60
* UCR.5: PCV Pinsp step size should be 1 not 0.2
* UCR.6: PCV ITS default should be 3, range 1-9
* UCR.7: PSV Pinsp default should be 15 not 10
* UCR.8: PSV ITS default should be 3, range 1-9
* UCR.9: PSV ETS min should be 5 not 0, max should be 60 not 50
* UCR.10: PSV apnea lag default should be 30, range 10-60
* UCR.11: PSV apnea RR range should be 4-50
* UCR.13: PSV apnea Pinsp range should be 2-40
* UCR.14 to UCR.18: The alarm limits for Pinsp, PEEP and Vtidal don't agree. In particular, min value of Pinsp is specified as a percentage rather than a fixed value.

**Comment by carmelopellegrino** [comment]
Hi @bs610, thank you for raising these up. Can I ask you to implement the due changes?
