### ISSUE TITLE
gui does not report firmware version

### ISSUE THREAD

**Issue by dd1dd1** [MechanicalVentilatorMilano/gui#252]
I do not see a button on the gui where the current firmware version is reported. ("get version"). Please add? K.O.

**Comment by carmelopellegrino** [comment]
Is it required? By the way, there is a change request board for these things :)

**Comment by dd1dd1** [comment]
"is it required?", it better be, how else do you turn the MVM machine off? (But for all I know, the machine does not even have an "on/off" power switch, the MVM sent to TRIUMF certainly does not).

But I do know that if you power-off the RPi (running the GUI), you will corrupt the linux filesystem on the SD card. You have to "shutdown -r now" first.
K.O.

**Comment by dd1dd1** [comment]
(I was looking at the wring bug report)

**Comment by dd1dd1** [comment]
I think a page reporting the firmware revision, the supervisor revision and the gui revision has to be somewhere. Otherwise, by looking at a machine how can you tell it has the correct software/firmware? K.O.,

**Comment by carmelopellegrino** [comment]
Such information is shown in the updater software. It could be useful to have it also shown in the GUI, maybe under the "Maintenance" tab in the settings pane but this change has to be reviewed by the change request board before being implemented.

**Comment by dd1dd1** [comment]
Carmelo, how do I submit this change request to the change request board? "gui should report the firmware version and the supervisor version".

**Comment by carmelopellegrino** [comment]
Hi Konstantin, you can write an email to Reiner indicating the reason for the requested change. Thanks
