### ISSUE TITLE
Need conversion factor for peep from get_all?

### ISSUE THREAD

**Issue by thomaslindner** [MechanicalVentilatorMilano/gui#254]
In the yaml file you specify the mbar->cmH20 conversions for pressure and peak variables that you get from get_all:

```
conversions:
    pressure: 1.01972 # mbar to cmH2O
    peak: 1.01972 # mbar to cmH2O
```

But you also ask for the variable 'peek' in get_all; doesn't that variable also need the same conversion factor?

**Comment by carmelopellegrino** [comment]
@thomaslindner, you are perfectly right! Good catch!
