### ISSUE TITLE
Temperature alarm

### ISSUE THREAD

**Issue by a-bombarda** [MechanicalVentilatorMilano/gui#259]
Requirement AL.28 is "The system shall raise an alarm if temperature exceeds 75°C".
The GUI does not comply with this alarm, and the temperature background is never set to red.

**Comment by javerom** [comment]
This can be configured via the `default_settings.yaml` file in a few lines. I've written a pull request to this effect.

**Comment by a-bombarda** [comment]
Thanks @javerom, I've looked to your pull request and approved it
