### ISSUE TITLE
ETS Default values

### ISSUE THREAD

**Issue by a-bombarda** [MechanicalVentilatorMilano/gui#265]
The ETS parameter is not present into the configuration file. Moreover, the allowed range (in requirement UCR.9) is 5-60%, while the GUI allows values in range 0-60%.

**Comment by javerom** [comment]
This ranges for this parameter is under `flow_trigger` in `default_settings` (perhaps misnamed or differently names). I have changed the settings so that the min is 5 and max is 60.

**Comment by a-bombarda** [comment]
Ok, thank you @javerom! I just approved the changes
