### ISSUE TITLE
Apnea Backup information missing

### ISSUE THREAD

**Issue by a-bombarda** [MechanicalVentilatorMilano/gui#267]
The requirement UCR.33 and UCR.34+31 requires the user to set:

- Target inspiratory pressure for apnea backup ventilation
- RR for apnea backup ventilation

These two parameters are missing in configuration section of the GUI

**Comment by carmelopellegrino** [comment]
Should be duplicate of issue #209, solved in PR #210

**Comment by a-bombarda** [comment]
Yes, correct
