### ISSUE TITLE
Connect pause buttons in menu

### ISSUE THREAD

**Issue by bs610** [MechanicalVentilatorMilano/gui#78]
The behaviour of pause buttons is:

- on press, set a parameter to 1 to the ESP32
- on release, set the same parameter to 0 to the ESP32

**Comment by bs610** [comment]
We discussed this at a Canadian meeting, and are concerned that "0" is only sent when the button is released. If the GUI crashes while the button is pressed, then the patient is left in a very bad state.

It seems like it would be better to continually send 1 while the button is pressed, and if the ESP32 notes that it hasn't seen a 1 for a while (a few seconds?) then it returns to normal state. I guess this needs to be discussed with those writing the ESP32 code.

**Comment by carmelopellegrino** [comment]
@bs610 Excellent point! This is something to be addressed to the firmware developer(s). So I think that for the moment we could keep this issue in the background and revive it when this point will be cleared.

**Comment by carmelopellegrino** [comment]
Latest info about it:

- [ ] start the inspiratory pause on the Qt `press` event:
```
set pause_inhale 1
```
and **keep** setting every 100ms until a `release` event. On `release`, immediately stop sending `set pause_inhale 1` and send `set pause_inhale 0`.

- [ ] start the expiratory pause on the Qt `press` event:
```
set pause_exhale 1
```
and **keep** setting every 100ms until a `release` event. On `release`, immediately stop sending `set pause_exhale 1` and send `set pause_exhale 0`.
