### ISSUE TITLE
add initial, start and alarm settings pages

### ISSUE THREAD

**Issue by carmelopellegrino** [MechanicalVentilatorMilano/gui#90]
- [x] add a fullscreen page, called the `initial` page, with two buttons:
    - `New patient`: this loads a default presets settings parameter (that used in ventilation)
    - `Resume ventilation`: this loads the settings used during the last ventilation
then both buttons move the GUI to the `start` page.
- [ ] add a fullscreen page, called the `start` page, with the following buttons:
    - `Start ventilation`: goes to the `home` page (that with plots)
    - `Settings`: goes to the `settings` page
    - `Circuit test`: issues the command (TBD) to the ESP32 to start a test procedure and then report about the results (TBD)
   moreover, there should be a `PEEP` monitor that updates every 0.2 secs or less its value asking to the hardware.
- [x] add a fullscreen page called `alarm settings` that allows to set threshold values (minimum and maximum) for the monitored observables  

this issue is better addressed right after the solution of issue #89

**Comment by javerom** [comment]
I've added the startup pages, but they are mostly superficial. Still todo:

- Functionality for new patients (new custom config file that is load)
- Don't start acquiring data or loading any config file until one of the buttons is pressed

**Comment by javerom** [comment]
I've been working on the alarms aspect of this. I have done the following:
- some organizational changes to make navigation less cluttered and more intuitive
- added alarms page with all available monitors
- the intention is to be able to change the limits and settings for all monitors, shown or not
