### ISSUE TITLE
Unit tests needed

### ISSUE THREAD

**Issue by marcodeltutto** [MechanicalVentilatorMilano/gui#91]
Unit tests are needed, running in a CI, to make sure that all new PRs don't break what is already existent, and that crucial features are always working. I will soon start a branch to work on this.

**Comment by marcodeltutto** [comment]
I am on branch `tests`. Using pytest and pytest-qt.

**Comment by marcodeltutto** [comment]
On branch `tests`, you can run tests by doing (from the head of the repo):
```
pytest tests
```

**Comment by garganti** [comment]
I think that now this can be closed, more tests are needed but the infrastructure is in place

**Comment by marcodeltutto** [comment]
Agree, closing it now.
